# Generated by Django 3.1.1 on 2020-09-11 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keychain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt', models.BinaryField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=200)),
                ('password_cipher', models.BinaryField(editable=True, max_length=300)),
                ('password_nonce', models.BinaryField(editable=True, max_length=300)),
                ('password_tag', models.BinaryField(editable=True, max_length=300)),
                ('keychain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keychains.keychain')),
            ],
        ),
    ]
