# Generated by Django 3.1.1 on 2020-09-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keychains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='password_cipher',
            field=models.BinaryField(editable=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='key',
            name='password_nonce',
            field=models.BinaryField(editable=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='key',
            name='password_tag',
            field=models.BinaryField(editable=True, max_length=300),
        ),
    ]
