export const INIT_KEYCHAIN_STARTED = "INIT_KEYCHAIN_STARTED";
export const INIT_KEYCHAIN_COMPLETED = "INIT_KEYCHAIN_COMPLETED";
export const INIT_KEYCHAIN_FAILED = "INIT_KEYCHAIN_FAILED";

export const LOGOUT_KEYCHAIN = "LOGOUT_KEYCHAIN";
