export const FETCH_KEYCHAINS_STARTED = "FETCH_KEYCHAINS_STARTED";
export const FETCH_KEYCHAINS_COMPLETED = "FETCH_KEYCHAINS_COMPLETED";
export const FETCH_KEYCHAINS_FAILED = "FETCH_KEYCHAINS_FAILED";

export const ADD_KEYCHAIN_STARTED = "ADD_KEYCHAIN_STARTED";
export const ADD_KEYCHAIN_COMPLETED = "ADD_KEYCHAIN_COMPLETED";
export const ADD_KEYCHAIN_FAILED = "ADD_KEYCHAIN_FAILED";

export const REMOVE_KEYCHAIN_STARTED = "REMOVE_KEYCHAIN_STARTED";
export const REMOVE_KEYCHAIN_COMPLETED = "REMOVE_KEYCHAIN_COMPLETED";
export const REMOVE_KEYCHAIN_FAILED = "REMOVE_KEYCHAIN_FAILED";