export const FETCH_KEYS_STARTED = "FETCH_KEYS_STARTED";
export const FETCH_KEYS_COMPLETED = "FETCH_KEYS_COMPLETED";
export const FETCH_KEYS_FAILED = "FETCH_KEYS_FAILED";

export const ADD_KEY_STARTED = "ADD_KEY_STARTED";
export const ADD_KEY_COMPLETED = "ADD_KEY_COMPLETED";
export const ADD_KEY_FAILED = "ADD_KEY_FAILED";

export const GET_KEY_PASSWORD_STARTED = "GET_KEY_PASSWORD_STARTED";
export const GET_KEY_PASSWORD_COMPLETED = "GET_KEY_PASSWORD_COMPLETED";
export const GET_KEY_PASSWORD_FAILED = "GET_KEY_PASSWORD_FAILED";

export const REMOVE_KEY_STARTED = "REMOVE_KEY_STARTED";
export const REMOVE_KEY_COMPLETED = "REMOVE_KEY_COMPLETED";
export const REMOVE_KEY_FAILED = "REMOVE_KEY_FAILED";
